// Code generated by protoc-gen-go. DO NOT EDIT.
// source: satsvc.proto

package satsvc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SatRequest struct {
	NoradNumber          int32    `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SatRequest) Reset()         { *m = SatRequest{} }
func (m *SatRequest) String() string { return proto.CompactTextString(m) }
func (*SatRequest) ProtoMessage()    {}
func (*SatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_443327da0f91cbfd, []int{0}
}
func (m *SatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatRequest.Unmarshal(m, b)
}
func (m *SatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatRequest.Marshal(b, m, deterministic)
}
func (dst *SatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatRequest.Merge(dst, src)
}
func (m *SatRequest) XXX_Size() int {
	return xxx_messageInfo_SatRequest.Size(m)
}
func (m *SatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SatRequest proto.InternalMessageInfo

func (m *SatRequest) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

type SatInfosResponse struct {
	NoradNumber          int32                `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tle1                 string               `protobuf:"bytes,3,opt,name=tle1,proto3" json:"tle1,omitempty"`
	Tle2                 string               `protobuf:"bytes,4,opt,name=tle2,proto3" json:"tle2,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SatInfosResponse) Reset()         { *m = SatInfosResponse{} }
func (m *SatInfosResponse) String() string { return proto.CompactTextString(m) }
func (*SatInfosResponse) ProtoMessage()    {}
func (*SatInfosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_443327da0f91cbfd, []int{1}
}
func (m *SatInfosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatInfosResponse.Unmarshal(m, b)
}
func (m *SatInfosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatInfosResponse.Marshal(b, m, deterministic)
}
func (dst *SatInfosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatInfosResponse.Merge(dst, src)
}
func (m *SatInfosResponse) XXX_Size() int {
	return xxx_messageInfo_SatInfosResponse.Size(m)
}
func (m *SatInfosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SatInfosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SatInfosResponse proto.InternalMessageInfo

func (m *SatInfosResponse) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

func (m *SatInfosResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SatInfosResponse) GetTle1() string {
	if m != nil {
		return m.Tle1
	}
	return ""
}

func (m *SatInfosResponse) GetTle2() string {
	if m != nil {
		return m.Tle2
	}
	return ""
}

func (m *SatInfosResponse) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type Location struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude             float64  `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_443327da0f91cbfd, []int{2}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

type Observation struct {
	NoradNumber          int32     `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	SatLocation          *Location `protobuf:"bytes,2,opt,name=sat_location,json=satLocation,proto3" json:"sat_location,omitempty"`
	Azimuth              float64   `protobuf:"fixed64,3,opt,name=azimuth,proto3" json:"azimuth,omitempty"`
	Elevation            float64   `protobuf:"fixed64,4,opt,name=elevation,proto3" json:"elevation,omitempty"`
	Range                float64   `protobuf:"fixed64,5,opt,name=range,proto3" json:"range,omitempty"`
	RangeRate            float64   `protobuf:"fixed64,6,opt,name=range_rate,json=rangeRate,proto3" json:"range_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Observation) Reset()         { *m = Observation{} }
func (m *Observation) String() string { return proto.CompactTextString(m) }
func (*Observation) ProtoMessage()    {}
func (*Observation) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_443327da0f91cbfd, []int{3}
}
func (m *Observation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Observation.Unmarshal(m, b)
}
func (m *Observation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Observation.Marshal(b, m, deterministic)
}
func (dst *Observation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Observation.Merge(dst, src)
}
func (m *Observation) XXX_Size() int {
	return xxx_messageInfo_Observation.Size(m)
}
func (m *Observation) XXX_DiscardUnknown() {
	xxx_messageInfo_Observation.DiscardUnknown(m)
}

var xxx_messageInfo_Observation proto.InternalMessageInfo

func (m *Observation) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

func (m *Observation) GetSatLocation() *Location {
	if m != nil {
		return m.SatLocation
	}
	return nil
}

func (m *Observation) GetAzimuth() float64 {
	if m != nil {
		return m.Azimuth
	}
	return 0
}

func (m *Observation) GetElevation() float64 {
	if m != nil {
		return m.Elevation
	}
	return 0
}

func (m *Observation) GetRange() float64 {
	if m != nil {
		return m.Range
	}
	return 0
}

func (m *Observation) GetRangeRate() float64 {
	if m != nil {
		return m.RangeRate
	}
	return 0
}

type SatLocationRequest struct {
	NoradNumber          int32                `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SatLocationRequest) Reset()         { *m = SatLocationRequest{} }
func (m *SatLocationRequest) String() string { return proto.CompactTextString(m) }
func (*SatLocationRequest) ProtoMessage()    {}
func (*SatLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_443327da0f91cbfd, []int{4}
}
func (m *SatLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatLocationRequest.Unmarshal(m, b)
}
func (m *SatLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatLocationRequest.Marshal(b, m, deterministic)
}
func (dst *SatLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatLocationRequest.Merge(dst, src)
}
func (m *SatLocationRequest) XXX_Size() int {
	return xxx_messageInfo_SatLocationRequest.Size(m)
}
func (m *SatLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SatLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SatLocationRequest proto.InternalMessageInfo

func (m *SatLocationRequest) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

func (m *SatLocationRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type SatLocationFromObsRequest struct {
	NoradNumber          int32     `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	ObserverLocation     *Location `protobuf:"bytes,2,opt,name=observer_location,json=observerLocation,proto3" json:"observer_location,omitempty"`
	StepsMs              int32     `protobuf:"varint,3,opt,name=steps_ms,json=stepsMs,proto3" json:"steps_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SatLocationFromObsRequest) Reset()         { *m = SatLocationFromObsRequest{} }
func (m *SatLocationFromObsRequest) String() string { return proto.CompactTextString(m) }
func (*SatLocationFromObsRequest) ProtoMessage()    {}
func (*SatLocationFromObsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_443327da0f91cbfd, []int{5}
}
func (m *SatLocationFromObsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatLocationFromObsRequest.Unmarshal(m, b)
}
func (m *SatLocationFromObsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatLocationFromObsRequest.Marshal(b, m, deterministic)
}
func (dst *SatLocationFromObsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatLocationFromObsRequest.Merge(dst, src)
}
func (m *SatLocationFromObsRequest) XXX_Size() int {
	return xxx_messageInfo_SatLocationFromObsRequest.Size(m)
}
func (m *SatLocationFromObsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SatLocationFromObsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SatLocationFromObsRequest proto.InternalMessageInfo

func (m *SatLocationFromObsRequest) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

func (m *SatLocationFromObsRequest) GetObserverLocation() *Location {
	if m != nil {
		return m.ObserverLocation
	}
	return nil
}

func (m *SatLocationFromObsRequest) GetStepsMs() int32 {
	if m != nil {
		return m.StepsMs
	}
	return 0
}

type GenPassesRequest struct {
	NoradNumber          int32                `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	ObserverLocation     *Location            `protobuf:"bytes,2,opt,name=observer_location,json=observerLocation,proto3" json:"observer_location,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	StopTime             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=stop_time,json=stopTime,proto3" json:"stop_time,omitempty"`
	StepSeconds          int32                `protobuf:"varint,5,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GenPassesRequest) Reset()         { *m = GenPassesRequest{} }
func (m *GenPassesRequest) String() string { return proto.CompactTextString(m) }
func (*GenPassesRequest) ProtoMessage()    {}
func (*GenPassesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_443327da0f91cbfd, []int{6}
}
func (m *GenPassesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenPassesRequest.Unmarshal(m, b)
}
func (m *GenPassesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenPassesRequest.Marshal(b, m, deterministic)
}
func (dst *GenPassesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenPassesRequest.Merge(dst, src)
}
func (m *GenPassesRequest) XXX_Size() int {
	return xxx_messageInfo_GenPassesRequest.Size(m)
}
func (m *GenPassesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenPassesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenPassesRequest proto.InternalMessageInfo

func (m *GenPassesRequest) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

func (m *GenPassesRequest) GetObserverLocation() *Location {
	if m != nil {
		return m.ObserverLocation
	}
	return nil
}

func (m *GenPassesRequest) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *GenPassesRequest) GetStopTime() *timestamp.Timestamp {
	if m != nil {
		return m.StopTime
	}
	return nil
}

func (m *GenPassesRequest) GetStepSeconds() int32 {
	if m != nil {
		return m.StepSeconds
	}
	return 0
}

type Pass struct {
	Aos                  *timestamp.Timestamp `protobuf:"bytes,1,opt,name=aos,proto3" json:"aos,omitempty"`
	Los                  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=los,proto3" json:"los,omitempty"`
	AosAzimuth           float64              `protobuf:"fixed64,3,opt,name=aos_azimuth,json=aosAzimuth,proto3" json:"aos_azimuth,omitempty"`
	LosAzimuth           float64              `protobuf:"fixed64,4,opt,name=los_azimuth,json=losAzimuth,proto3" json:"los_azimuth,omitempty"`
	MaxElevation         float64              `protobuf:"fixed64,5,opt,name=max_elevation,json=maxElevation,proto3" json:"max_elevation,omitempty"`
	AosRangeRate         float64              `protobuf:"fixed64,6,opt,name=aos_range_rate,json=aosRangeRate,proto3" json:"aos_range_rate,omitempty"`
	LosRangeRate         float64              `protobuf:"fixed64,7,opt,name=los_range_rate,json=losRangeRate,proto3" json:"los_range_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pass) Reset()         { *m = Pass{} }
func (m *Pass) String() string { return proto.CompactTextString(m) }
func (*Pass) ProtoMessage()    {}
func (*Pass) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_443327da0f91cbfd, []int{7}
}
func (m *Pass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pass.Unmarshal(m, b)
}
func (m *Pass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pass.Marshal(b, m, deterministic)
}
func (dst *Pass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pass.Merge(dst, src)
}
func (m *Pass) XXX_Size() int {
	return xxx_messageInfo_Pass.Size(m)
}
func (m *Pass) XXX_DiscardUnknown() {
	xxx_messageInfo_Pass.DiscardUnknown(m)
}

var xxx_messageInfo_Pass proto.InternalMessageInfo

func (m *Pass) GetAos() *timestamp.Timestamp {
	if m != nil {
		return m.Aos
	}
	return nil
}

func (m *Pass) GetLos() *timestamp.Timestamp {
	if m != nil {
		return m.Los
	}
	return nil
}

func (m *Pass) GetAosAzimuth() float64 {
	if m != nil {
		return m.AosAzimuth
	}
	return 0
}

func (m *Pass) GetLosAzimuth() float64 {
	if m != nil {
		return m.LosAzimuth
	}
	return 0
}

func (m *Pass) GetMaxElevation() float64 {
	if m != nil {
		return m.MaxElevation
	}
	return 0
}

func (m *Pass) GetAosRangeRate() float64 {
	if m != nil {
		return m.AosRangeRate
	}
	return 0
}

func (m *Pass) GetLosRangeRate() float64 {
	if m != nil {
		return m.LosRangeRate
	}
	return 0
}

type Passes struct {
	Passes               []*Pass  `protobuf:"bytes,1,rep,name=passes,proto3" json:"passes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Passes) Reset()         { *m = Passes{} }
func (m *Passes) String() string { return proto.CompactTextString(m) }
func (*Passes) ProtoMessage()    {}
func (*Passes) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_443327da0f91cbfd, []int{8}
}
func (m *Passes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Passes.Unmarshal(m, b)
}
func (m *Passes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Passes.Marshal(b, m, deterministic)
}
func (dst *Passes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Passes.Merge(dst, src)
}
func (m *Passes) XXX_Size() int {
	return xxx_messageInfo_Passes.Size(m)
}
func (m *Passes) XXX_DiscardUnknown() {
	xxx_messageInfo_Passes.DiscardUnknown(m)
}

var xxx_messageInfo_Passes proto.InternalMessageInfo

func (m *Passes) GetPasses() []*Pass {
	if m != nil {
		return m.Passes
	}
	return nil
}

func init() {
	proto.RegisterType((*SatRequest)(nil), "SatRequest")
	proto.RegisterType((*SatInfosResponse)(nil), "SatInfosResponse")
	proto.RegisterType((*Location)(nil), "Location")
	proto.RegisterType((*Observation)(nil), "Observation")
	proto.RegisterType((*SatLocationRequest)(nil), "SatLocationRequest")
	proto.RegisterType((*SatLocationFromObsRequest)(nil), "SatLocationFromObsRequest")
	proto.RegisterType((*GenPassesRequest)(nil), "GenPassesRequest")
	proto.RegisterType((*Pass)(nil), "Pass")
	proto.RegisterType((*Passes)(nil), "Passes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PredictionClient is the client API for Prediction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PredictionClient interface {
	SatInfos(ctx context.Context, in *SatRequest, opts ...grpc.CallOption) (*SatInfosResponse, error)
	SatLocation(ctx context.Context, in *SatLocationRequest, opts ...grpc.CallOption) (*Location, error)
	SatLocationFromObs(ctx context.Context, in *SatLocationFromObsRequest, opts ...grpc.CallOption) (Prediction_SatLocationFromObsClient, error)
	GenPasses(ctx context.Context, in *GenPassesRequest, opts ...grpc.CallOption) (*Passes, error)
}

type predictionClient struct {
	cc *grpc.ClientConn
}

func NewPredictionClient(cc *grpc.ClientConn) PredictionClient {
	return &predictionClient{cc}
}

func (c *predictionClient) SatInfos(ctx context.Context, in *SatRequest, opts ...grpc.CallOption) (*SatInfosResponse, error) {
	out := new(SatInfosResponse)
	err := c.cc.Invoke(ctx, "/Prediction/SatInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictionClient) SatLocation(ctx context.Context, in *SatLocationRequest, opts ...grpc.CallOption) (*Location, error) {
	out := new(Location)
	err := c.cc.Invoke(ctx, "/Prediction/SatLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictionClient) SatLocationFromObs(ctx context.Context, in *SatLocationFromObsRequest, opts ...grpc.CallOption) (Prediction_SatLocationFromObsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Prediction_serviceDesc.Streams[0], "/Prediction/SatLocationFromObs", opts...)
	if err != nil {
		return nil, err
	}
	x := &predictionSatLocationFromObsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Prediction_SatLocationFromObsClient interface {
	Recv() (*Observation, error)
	grpc.ClientStream
}

type predictionSatLocationFromObsClient struct {
	grpc.ClientStream
}

func (x *predictionSatLocationFromObsClient) Recv() (*Observation, error) {
	m := new(Observation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *predictionClient) GenPasses(ctx context.Context, in *GenPassesRequest, opts ...grpc.CallOption) (*Passes, error) {
	out := new(Passes)
	err := c.cc.Invoke(ctx, "/Prediction/GenPasses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PredictionServer is the server API for Prediction service.
type PredictionServer interface {
	SatInfos(context.Context, *SatRequest) (*SatInfosResponse, error)
	SatLocation(context.Context, *SatLocationRequest) (*Location, error)
	SatLocationFromObs(*SatLocationFromObsRequest, Prediction_SatLocationFromObsServer) error
	GenPasses(context.Context, *GenPassesRequest) (*Passes, error)
}

func RegisterPredictionServer(s *grpc.Server, srv PredictionServer) {
	s.RegisterService(&_Prediction_serviceDesc, srv)
}

func _Prediction_SatInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictionServer).SatInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Prediction/SatInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictionServer).SatInfos(ctx, req.(*SatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prediction_SatLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SatLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictionServer).SatLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Prediction/SatLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictionServer).SatLocation(ctx, req.(*SatLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prediction_SatLocationFromObs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SatLocationFromObsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PredictionServer).SatLocationFromObs(m, &predictionSatLocationFromObsServer{stream})
}

type Prediction_SatLocationFromObsServer interface {
	Send(*Observation) error
	grpc.ServerStream
}

type predictionSatLocationFromObsServer struct {
	grpc.ServerStream
}

func (x *predictionSatLocationFromObsServer) Send(m *Observation) error {
	return x.ServerStream.SendMsg(m)
}

func _Prediction_GenPasses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenPassesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictionServer).GenPasses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Prediction/GenPasses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictionServer).GenPasses(ctx, req.(*GenPassesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Prediction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Prediction",
	HandlerType: (*PredictionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SatInfos",
			Handler:    _Prediction_SatInfos_Handler,
		},
		{
			MethodName: "SatLocation",
			Handler:    _Prediction_SatLocation_Handler,
		},
		{
			MethodName: "GenPasses",
			Handler:    _Prediction_GenPasses_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SatLocationFromObs",
			Handler:       _Prediction_SatLocationFromObs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "satsvc.proto",
}

func init() { proto.RegisterFile("satsvc.proto", fileDescriptor_satsvc_443327da0f91cbfd) }

var fileDescriptor_satsvc_443327da0f91cbfd = []byte{
	// 664 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0x8e, 0xf3, 0x9f, 0xd9, 0x80, 0x5a, 0xc3, 0x61, 0xbb, 0xa2, 0x6a, 0x6a, 0x90, 0x08, 0x52,
	0xe5, 0x40, 0x90, 0x40, 0x88, 0x13, 0x48, 0x80, 0x90, 0x80, 0x56, 0x0e, 0xf7, 0xc5, 0x49, 0xdc,
	0x10, 0x69, 0x77, 0xbd, 0xac, 0x9d, 0xaa, 0xe2, 0xcc, 0x0b, 0x70, 0xe0, 0x35, 0x78, 0x11, 0xde,
	0x80, 0xa7, 0x41, 0xb6, 0xf7, 0x27, 0x6d, 0x45, 0x13, 0x2e, 0xdc, 0x3c, 0xdf, 0x7e, 0xb3, 0x33,
	0xf3, 0xf9, 0x1b, 0x43, 0x5f, 0x71, 0xad, 0xce, 0x66, 0x34, 0xcd, 0xa4, 0x96, 0xc1, 0xc1, 0x42,
	0xca, 0x45, 0x24, 0x46, 0x36, 0x9a, 0xae, 0x4e, 0x47, 0x7a, 0x19, 0x0b, 0xa5, 0x79, 0x9c, 0x3a,
	0x02, 0x19, 0x01, 0x4c, 0xb8, 0x66, 0xe2, 0xcb, 0x4a, 0x28, 0x8d, 0x0f, 0xa1, 0x9f, 0xc8, 0x8c,
	0xcf, 0xc3, 0x64, 0x15, 0x4f, 0x45, 0xe6, 0xa3, 0x01, 0x1a, 0xb6, 0x98, 0x67, 0xb1, 0x0f, 0x16,
	0x22, 0x3f, 0x11, 0xec, 0x4c, 0xb8, 0x7e, 0x9b, 0x9c, 0x4a, 0xc5, 0x84, 0x4a, 0x65, 0xa2, 0xc4,
	0x16, 0x79, 0x18, 0x43, 0x33, 0xe1, 0xb1, 0xf0, 0xeb, 0x03, 0x34, 0xec, 0x31, 0x7b, 0x36, 0x98,
	0x8e, 0xc4, 0x23, 0xbf, 0xe1, 0x30, 0x73, 0xce, 0xb1, 0xb1, 0xdf, 0x2c, 0xb1, 0x31, 0x7e, 0x0e,
	0xde, 0x2a, 0x9d, 0x73, 0x2d, 0x42, 0xd3, 0xbe, 0xdf, 0x1a, 0xa0, 0xa1, 0x37, 0x0e, 0xa8, 0x9b,
	0x8d, 0x16, 0xb3, 0xd1, 0x8f, 0xc5, 0x6c, 0x0c, 0x1c, 0xdd, 0x00, 0xe4, 0x13, 0x74, 0xdf, 0xc9,
	0x19, 0xd7, 0x4b, 0x99, 0xe0, 0x00, 0xba, 0x11, 0xd7, 0x4b, 0xbd, 0x9a, 0x0b, 0xdb, 0x23, 0x62,
	0x65, 0x8c, 0xef, 0x40, 0x2f, 0x92, 0xc9, 0xc2, 0x7d, 0xac, 0xdb, 0x8f, 0x15, 0x60, 0x32, 0x79,
	0x94, 0x67, 0x36, 0x5c, 0x66, 0x11, 0x93, 0x5f, 0x08, 0xbc, 0xe3, 0xa9, 0x12, 0xd9, 0x99, 0xab,
	0xb2, 0x85, 0x1a, 0x47, 0xf6, 0x9e, 0xc2, 0x28, 0x6f, 0xcc, 0xd6, 0xf3, 0xc6, 0x3d, 0x5a, 0x74,
	0xca, 0x3c, 0xc5, 0x75, 0xd9, 0xb6, 0x0f, 0x1d, 0xfe, 0x75, 0x19, 0xaf, 0xf4, 0xe7, 0xbc, 0x76,
	0x11, 0x9a, 0xa6, 0x45, 0x24, 0x5c, 0x5d, 0x2b, 0x19, 0x62, 0x15, 0x80, 0x6f, 0x43, 0x2b, 0xe3,
	0xc9, 0xc2, 0x29, 0x86, 0x98, 0x0b, 0xf0, 0x3e, 0x80, 0x3d, 0x84, 0x19, 0xd7, 0xc2, 0x6f, 0xbb,
	0x24, 0x8b, 0x30, 0xae, 0x05, 0x59, 0x00, 0x9e, 0x54, 0xb5, 0xb7, 0x77, 0x06, 0xa6, 0xd0, 0xb4,
	0xd7, 0x53, 0xdf, 0x78, 0x3d, 0x96, 0x47, 0xbe, 0x23, 0xd8, 0x5b, 0xab, 0xf4, 0x3a, 0x93, 0xf1,
	0xf1, 0x54, 0xfd, 0x43, 0xc1, 0x27, 0xb0, 0x2b, 0xad, 0xec, 0x22, 0xbb, 0x46, 0xc9, 0x9d, 0x82,
	0x53, 0xca, 0xb9, 0x07, 0x5d, 0xa5, 0x45, 0xaa, 0xc2, 0x58, 0x59, 0x3d, 0x5b, 0xac, 0x63, 0xe3,
	0xf7, 0x8a, 0x7c, 0xab, 0xc3, 0xce, 0x1b, 0x91, 0x9c, 0x70, 0xa5, 0xc4, 0xff, 0x68, 0xe5, 0x19,
	0x80, 0xd2, 0x3c, 0xd3, 0xce, 0xd8, 0x8d, 0x8d, 0xca, 0xf5, 0x2c, 0xdb, 0xc4, 0xf8, 0x29, 0xf4,
	0x94, 0x96, 0xa9, 0xcb, 0x6c, 0x6e, 0xcc, 0xec, 0x1a, 0xb2, 0x4d, 0x3c, 0x84, 0xbe, 0x19, 0x37,
	0x54, 0x62, 0x26, 0x93, 0xb9, 0xb2, 0xe6, 0x68, 0x31, 0xcf, 0x60, 0x13, 0x07, 0x91, 0x1f, 0x75,
	0x68, 0x1a, 0x0d, 0xf0, 0x11, 0x34, 0xb8, 0x54, 0x76, 0xe2, 0xeb, 0x7f, 0x6f, 0x68, 0x86, 0x1d,
	0x49, 0xb5, 0x85, 0x01, 0x0c, 0x0d, 0x1f, 0x80, 0xc7, 0xa5, 0x0a, 0x2f, 0x3a, 0x1b, 0xb8, 0x54,
	0x2f, 0x72, 0x73, 0x1f, 0x80, 0x17, 0xad, 0x11, 0x9c, 0xbd, 0x21, 0xaa, 0x08, 0x77, 0xe1, 0x46,
	0xcc, 0xcf, 0xc3, 0x6a, 0x03, 0x9c, 0xcf, 0xfb, 0x31, 0x3f, 0x7f, 0x55, 0x2e, 0xc1, 0x3d, 0xb8,
	0x69, 0xca, 0x5c, 0xb1, 0x7c, 0x9f, 0x4b, 0xc5, 0x0a, 0xd7, 0x1b, 0x56, 0x74, 0x91, 0xd5, 0x71,
	0xac, 0x68, 0x8d, 0x45, 0xee, 0x43, 0xdb, 0x59, 0x03, 0xef, 0x43, 0x3b, 0xb5, 0x27, 0x1f, 0x0d,
	0x1a, 0x43, 0x6f, 0xdc, 0xa2, 0xe6, 0x03, 0xcb, 0xc1, 0xf1, 0x6f, 0x04, 0x70, 0x92, 0x89, 0xf9,
	0x72, 0x66, 0x7b, 0x38, 0x82, 0x6e, 0xf1, 0x66, 0x62, 0x8f, 0x56, 0x0f, 0x6e, 0xb0, 0x4b, 0x2f,
	0xbf, 0xa5, 0xa4, 0x86, 0x47, 0xe0, 0xad, 0xed, 0x05, 0xbe, 0x45, 0xaf, 0xee, 0x63, 0x50, 0xb9,
	0x8a, 0xd4, 0xf0, 0xcb, 0x0b, 0x2b, 0x9b, 0x2f, 0x12, 0x0e, 0xe8, 0x5f, 0xb7, 0x2b, 0xe8, 0xd3,
	0xb5, 0x07, 0x8b, 0xd4, 0x1e, 0x22, 0xfc, 0x00, 0x7a, 0xa5, 0xf1, 0xf1, 0x2e, 0xbd, 0xbc, 0x04,
	0x41, 0x87, 0xba, 0x98, 0xd4, 0xa6, 0x6d, 0x7b, 0xa3, 0x8f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xe2, 0xe1, 0xb2, 0x58, 0x6b, 0x06, 0x00, 0x00,
}
