// Code generated by protoc-gen-go. DO NOT EDIT.
// source: satsvc.proto

package satsvc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SatInfos struct {
	NoradNumber          int32                `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tle1                 string               `protobuf:"bytes,3,opt,name=tle1,proto3" json:"tle1,omitempty"`
	Tle2                 string               `protobuf:"bytes,4,opt,name=tle2,proto3" json:"tle2,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SatInfos) Reset()         { *m = SatInfos{} }
func (m *SatInfos) String() string { return proto.CompactTextString(m) }
func (*SatInfos) ProtoMessage()    {}
func (*SatInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{0}
}
func (m *SatInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatInfos.Unmarshal(m, b)
}
func (m *SatInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatInfos.Marshal(b, m, deterministic)
}
func (dst *SatInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatInfos.Merge(dst, src)
}
func (m *SatInfos) XXX_Size() int {
	return xxx_messageInfo_SatInfos.Size(m)
}
func (m *SatInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_SatInfos.DiscardUnknown(m)
}

var xxx_messageInfo_SatInfos proto.InternalMessageInfo

func (m *SatInfos) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

func (m *SatInfos) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SatInfos) GetTle1() string {
	if m != nil {
		return m.Tle1
	}
	return ""
}

func (m *SatInfos) GetTle2() string {
	if m != nil {
		return m.Tle2
	}
	return ""
}

func (m *SatInfos) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type SatsInfosResponse struct {
	SatInfos             []*SatInfos `protobuf:"bytes,1,rep,name=sat_infos,json=satInfos,proto3" json:"sat_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SatsInfosResponse) Reset()         { *m = SatsInfosResponse{} }
func (m *SatsInfosResponse) String() string { return proto.CompactTextString(m) }
func (*SatsInfosResponse) ProtoMessage()    {}
func (*SatsInfosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{1}
}
func (m *SatsInfosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatsInfosResponse.Unmarshal(m, b)
}
func (m *SatsInfosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatsInfosResponse.Marshal(b, m, deterministic)
}
func (dst *SatsInfosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatsInfosResponse.Merge(dst, src)
}
func (m *SatsInfosResponse) XXX_Size() int {
	return xxx_messageInfo_SatsInfosResponse.Size(m)
}
func (m *SatsInfosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SatsInfosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SatsInfosResponse proto.InternalMessageInfo

func (m *SatsInfosResponse) GetSatInfos() []*SatInfos {
	if m != nil {
		return m.SatInfos
	}
	return nil
}

type Location struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude             float64  `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{2}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

type SatLocation struct {
	NoradNumber          int32    `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude             float64  `protobuf:"fixed64,4,opt,name=altitude,proto3" json:"altitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SatLocation) Reset()         { *m = SatLocation{} }
func (m *SatLocation) String() string { return proto.CompactTextString(m) }
func (*SatLocation) ProtoMessage()    {}
func (*SatLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{3}
}
func (m *SatLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatLocation.Unmarshal(m, b)
}
func (m *SatLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatLocation.Marshal(b, m, deterministic)
}
func (dst *SatLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatLocation.Merge(dst, src)
}
func (m *SatLocation) XXX_Size() int {
	return xxx_messageInfo_SatLocation.Size(m)
}
func (m *SatLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_SatLocation.DiscardUnknown(m)
}

var xxx_messageInfo_SatLocation proto.InternalMessageInfo

func (m *SatLocation) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

func (m *SatLocation) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *SatLocation) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *SatLocation) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

type Category struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sats                 []int32  `protobuf:"varint,3,rep,packed,name=sats,proto3" json:"sats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{4}
}
func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (dst *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(dst, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetSats() []int32 {
	if m != nil {
		return m.Sats
	}
	return nil
}

type SatsLocationsResponse struct {
	SatLocations         []*SatLocation `protobuf:"bytes,1,rep,name=sat_locations,json=satLocations,proto3" json:"sat_locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SatsLocationsResponse) Reset()         { *m = SatsLocationsResponse{} }
func (m *SatsLocationsResponse) String() string { return proto.CompactTextString(m) }
func (*SatsLocationsResponse) ProtoMessage()    {}
func (*SatsLocationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{5}
}
func (m *SatsLocationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatsLocationsResponse.Unmarshal(m, b)
}
func (m *SatsLocationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatsLocationsResponse.Marshal(b, m, deterministic)
}
func (dst *SatsLocationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatsLocationsResponse.Merge(dst, src)
}
func (m *SatsLocationsResponse) XXX_Size() int {
	return xxx_messageInfo_SatsLocationsResponse.Size(m)
}
func (m *SatsLocationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SatsLocationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SatsLocationsResponse proto.InternalMessageInfo

func (m *SatsLocationsResponse) GetSatLocations() []*SatLocation {
	if m != nil {
		return m.SatLocations
	}
	return nil
}

type CategoriesResponse struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CategoriesResponse) Reset()         { *m = CategoriesResponse{} }
func (m *CategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*CategoriesResponse) ProtoMessage()    {}
func (*CategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{6}
}
func (m *CategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoriesResponse.Unmarshal(m, b)
}
func (m *CategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoriesResponse.Marshal(b, m, deterministic)
}
func (dst *CategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoriesResponse.Merge(dst, src)
}
func (m *CategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_CategoriesResponse.Size(m)
}
func (m *CategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CategoriesResponse proto.InternalMessageInfo

func (m *CategoriesResponse) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type Observation struct {
	NoradNumber          int32     `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	SatLocation          *Location `protobuf:"bytes,2,opt,name=sat_location,json=satLocation,proto3" json:"sat_location,omitempty"`
	Azimuth              float64   `protobuf:"fixed64,3,opt,name=azimuth,proto3" json:"azimuth,omitempty"`
	Elevation            float64   `protobuf:"fixed64,4,opt,name=elevation,proto3" json:"elevation,omitempty"`
	Range                float64   `protobuf:"fixed64,5,opt,name=range,proto3" json:"range,omitempty"`
	RangeRate            float64   `protobuf:"fixed64,6,opt,name=range_rate,json=rangeRate,proto3" json:"range_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Observation) Reset()         { *m = Observation{} }
func (m *Observation) String() string { return proto.CompactTextString(m) }
func (*Observation) ProtoMessage()    {}
func (*Observation) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{7}
}
func (m *Observation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Observation.Unmarshal(m, b)
}
func (m *Observation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Observation.Marshal(b, m, deterministic)
}
func (dst *Observation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Observation.Merge(dst, src)
}
func (m *Observation) XXX_Size() int {
	return xxx_messageInfo_Observation.Size(m)
}
func (m *Observation) XXX_DiscardUnknown() {
	xxx_messageInfo_Observation.DiscardUnknown(m)
}

var xxx_messageInfo_Observation proto.InternalMessageInfo

func (m *Observation) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

func (m *Observation) GetSatLocation() *Location {
	if m != nil {
		return m.SatLocation
	}
	return nil
}

func (m *Observation) GetAzimuth() float64 {
	if m != nil {
		return m.Azimuth
	}
	return 0
}

func (m *Observation) GetElevation() float64 {
	if m != nil {
		return m.Elevation
	}
	return 0
}

func (m *Observation) GetRange() float64 {
	if m != nil {
		return m.Range
	}
	return 0
}

func (m *Observation) GetRangeRate() float64 {
	if m != nil {
		return m.RangeRate
	}
	return 0
}

type SatsRequest struct {
	NoradNumbers         []int32  `protobuf:"varint,1,rep,packed,name=norad_numbers,json=noradNumbers,proto3" json:"norad_numbers,omitempty"`
	Category             int32    `protobuf:"varint,2,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SatsRequest) Reset()         { *m = SatsRequest{} }
func (m *SatsRequest) String() string { return proto.CompactTextString(m) }
func (*SatsRequest) ProtoMessage()    {}
func (*SatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{8}
}
func (m *SatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatsRequest.Unmarshal(m, b)
}
func (m *SatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatsRequest.Marshal(b, m, deterministic)
}
func (dst *SatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatsRequest.Merge(dst, src)
}
func (m *SatsRequest) XXX_Size() int {
	return xxx_messageInfo_SatsRequest.Size(m)
}
func (m *SatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SatsRequest proto.InternalMessageInfo

func (m *SatsRequest) GetNoradNumbers() []int32 {
	if m != nil {
		return m.NoradNumbers
	}
	return nil
}

func (m *SatsRequest) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

type SatLocationFromObsRequest struct {
	NoradNumbers         []int32   `protobuf:"varint,1,rep,packed,name=norad_numbers,json=noradNumbers,proto3" json:"norad_numbers,omitempty"`
	ObserverLocation     *Location `protobuf:"bytes,2,opt,name=observer_location,json=observerLocation,proto3" json:"observer_location,omitempty"`
	StepsMs              int32     `protobuf:"varint,3,opt,name=steps_ms,json=stepsMs,proto3" json:"steps_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SatLocationFromObsRequest) Reset()         { *m = SatLocationFromObsRequest{} }
func (m *SatLocationFromObsRequest) String() string { return proto.CompactTextString(m) }
func (*SatLocationFromObsRequest) ProtoMessage()    {}
func (*SatLocationFromObsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{9}
}
func (m *SatLocationFromObsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatLocationFromObsRequest.Unmarshal(m, b)
}
func (m *SatLocationFromObsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatLocationFromObsRequest.Marshal(b, m, deterministic)
}
func (dst *SatLocationFromObsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatLocationFromObsRequest.Merge(dst, src)
}
func (m *SatLocationFromObsRequest) XXX_Size() int {
	return xxx_messageInfo_SatLocationFromObsRequest.Size(m)
}
func (m *SatLocationFromObsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SatLocationFromObsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SatLocationFromObsRequest proto.InternalMessageInfo

func (m *SatLocationFromObsRequest) GetNoradNumbers() []int32 {
	if m != nil {
		return m.NoradNumbers
	}
	return nil
}

func (m *SatLocationFromObsRequest) GetObserverLocation() *Location {
	if m != nil {
		return m.ObserverLocation
	}
	return nil
}

func (m *SatLocationFromObsRequest) GetStepsMs() int32 {
	if m != nil {
		return m.StepsMs
	}
	return 0
}

type GenPassesRequest struct {
	NoradNumber          int32                `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	ObserverLocation     *Location            `protobuf:"bytes,2,opt,name=observer_location,json=observerLocation,proto3" json:"observer_location,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	StopTime             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=stop_time,json=stopTime,proto3" json:"stop_time,omitempty"`
	StepSeconds          int32                `protobuf:"varint,5,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`
	MinElevation         float64              `protobuf:"fixed64,6,opt,name=min_elevation,json=minElevation,proto3" json:"min_elevation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GenPassesRequest) Reset()         { *m = GenPassesRequest{} }
func (m *GenPassesRequest) String() string { return proto.CompactTextString(m) }
func (*GenPassesRequest) ProtoMessage()    {}
func (*GenPassesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{10}
}
func (m *GenPassesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenPassesRequest.Unmarshal(m, b)
}
func (m *GenPassesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenPassesRequest.Marshal(b, m, deterministic)
}
func (dst *GenPassesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenPassesRequest.Merge(dst, src)
}
func (m *GenPassesRequest) XXX_Size() int {
	return xxx_messageInfo_GenPassesRequest.Size(m)
}
func (m *GenPassesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenPassesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenPassesRequest proto.InternalMessageInfo

func (m *GenPassesRequest) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

func (m *GenPassesRequest) GetObserverLocation() *Location {
	if m != nil {
		return m.ObserverLocation
	}
	return nil
}

func (m *GenPassesRequest) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *GenPassesRequest) GetStopTime() *timestamp.Timestamp {
	if m != nil {
		return m.StopTime
	}
	return nil
}

func (m *GenPassesRequest) GetStepSeconds() int32 {
	if m != nil {
		return m.StepSeconds
	}
	return 0
}

func (m *GenPassesRequest) GetMinElevation() float64 {
	if m != nil {
		return m.MinElevation
	}
	return 0
}

type GenLocationsRequest struct {
	NoradNumbers         []int32              `protobuf:"varint,1,rep,packed,name=norad_numbers,json=noradNumbers,proto3" json:"norad_numbers,omitempty"`
	Category             int32                `protobuf:"varint,2,opt,name=category,proto3" json:"category,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	StopTime             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=stop_time,json=stopTime,proto3" json:"stop_time,omitempty"`
	StepSeconds          int32                `protobuf:"varint,5,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GenLocationsRequest) Reset()         { *m = GenLocationsRequest{} }
func (m *GenLocationsRequest) String() string { return proto.CompactTextString(m) }
func (*GenLocationsRequest) ProtoMessage()    {}
func (*GenLocationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{11}
}
func (m *GenLocationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenLocationsRequest.Unmarshal(m, b)
}
func (m *GenLocationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenLocationsRequest.Marshal(b, m, deterministic)
}
func (dst *GenLocationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenLocationsRequest.Merge(dst, src)
}
func (m *GenLocationsRequest) XXX_Size() int {
	return xxx_messageInfo_GenLocationsRequest.Size(m)
}
func (m *GenLocationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenLocationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenLocationsRequest proto.InternalMessageInfo

func (m *GenLocationsRequest) GetNoradNumbers() []int32 {
	if m != nil {
		return m.NoradNumbers
	}
	return nil
}

func (m *GenLocationsRequest) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *GenLocationsRequest) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *GenLocationsRequest) GetStopTime() *timestamp.Timestamp {
	if m != nil {
		return m.StopTime
	}
	return nil
}

func (m *GenLocationsRequest) GetStepSeconds() int32 {
	if m != nil {
		return m.StepSeconds
	}
	return 0
}

type GenLocationsResponse struct {
	Locations            []*GenLocations `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	StepSeconds          int32           `protobuf:"varint,2,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GenLocationsResponse) Reset()         { *m = GenLocationsResponse{} }
func (m *GenLocationsResponse) String() string { return proto.CompactTextString(m) }
func (*GenLocationsResponse) ProtoMessage()    {}
func (*GenLocationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{12}
}
func (m *GenLocationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenLocationsResponse.Unmarshal(m, b)
}
func (m *GenLocationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenLocationsResponse.Marshal(b, m, deterministic)
}
func (dst *GenLocationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenLocationsResponse.Merge(dst, src)
}
func (m *GenLocationsResponse) XXX_Size() int {
	return xxx_messageInfo_GenLocationsResponse.Size(m)
}
func (m *GenLocationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenLocationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenLocationsResponse proto.InternalMessageInfo

func (m *GenLocationsResponse) GetLocations() []*GenLocations {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *GenLocationsResponse) GetStepSeconds() int32 {
	if m != nil {
		return m.StepSeconds
	}
	return 0
}

type GenLocations struct {
	NoradNumber          int32       `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	Location             []*Location `protobuf:"bytes,2,rep,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GenLocations) Reset()         { *m = GenLocations{} }
func (m *GenLocations) String() string { return proto.CompactTextString(m) }
func (*GenLocations) ProtoMessage()    {}
func (*GenLocations) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{13}
}
func (m *GenLocations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenLocations.Unmarshal(m, b)
}
func (m *GenLocations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenLocations.Marshal(b, m, deterministic)
}
func (dst *GenLocations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenLocations.Merge(dst, src)
}
func (m *GenLocations) XXX_Size() int {
	return xxx_messageInfo_GenLocations.Size(m)
}
func (m *GenLocations) XXX_DiscardUnknown() {
	xxx_messageInfo_GenLocations.DiscardUnknown(m)
}

var xxx_messageInfo_GenLocations proto.InternalMessageInfo

func (m *GenLocations) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

func (m *GenLocations) GetLocation() []*Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Pass struct {
	Aos                  *timestamp.Timestamp `protobuf:"bytes,1,opt,name=aos,proto3" json:"aos,omitempty"`
	Los                  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=los,proto3" json:"los,omitempty"`
	AosAzimuth           float64              `protobuf:"fixed64,3,opt,name=aos_azimuth,json=aosAzimuth,proto3" json:"aos_azimuth,omitempty"`
	LosAzimuth           float64              `protobuf:"fixed64,4,opt,name=los_azimuth,json=losAzimuth,proto3" json:"los_azimuth,omitempty"`
	MaxElevation         float64              `protobuf:"fixed64,5,opt,name=max_elevation,json=maxElevation,proto3" json:"max_elevation,omitempty"`
	AosRangeRate         float64              `protobuf:"fixed64,6,opt,name=aos_range_rate,json=aosRangeRate,proto3" json:"aos_range_rate,omitempty"`
	LosRangeRate         float64              `protobuf:"fixed64,7,opt,name=los_range_rate,json=losRangeRate,proto3" json:"los_range_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pass) Reset()         { *m = Pass{} }
func (m *Pass) String() string { return proto.CompactTextString(m) }
func (*Pass) ProtoMessage()    {}
func (*Pass) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{14}
}
func (m *Pass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pass.Unmarshal(m, b)
}
func (m *Pass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pass.Marshal(b, m, deterministic)
}
func (dst *Pass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pass.Merge(dst, src)
}
func (m *Pass) XXX_Size() int {
	return xxx_messageInfo_Pass.Size(m)
}
func (m *Pass) XXX_DiscardUnknown() {
	xxx_messageInfo_Pass.DiscardUnknown(m)
}

var xxx_messageInfo_Pass proto.InternalMessageInfo

func (m *Pass) GetAos() *timestamp.Timestamp {
	if m != nil {
		return m.Aos
	}
	return nil
}

func (m *Pass) GetLos() *timestamp.Timestamp {
	if m != nil {
		return m.Los
	}
	return nil
}

func (m *Pass) GetAosAzimuth() float64 {
	if m != nil {
		return m.AosAzimuth
	}
	return 0
}

func (m *Pass) GetLosAzimuth() float64 {
	if m != nil {
		return m.LosAzimuth
	}
	return 0
}

func (m *Pass) GetMaxElevation() float64 {
	if m != nil {
		return m.MaxElevation
	}
	return 0
}

func (m *Pass) GetAosRangeRate() float64 {
	if m != nil {
		return m.AosRangeRate
	}
	return 0
}

func (m *Pass) GetLosRangeRate() float64 {
	if m != nil {
		return m.LosRangeRate
	}
	return 0
}

type Passes struct {
	Passes               []*Pass  `protobuf:"bytes,1,rep,name=passes,proto3" json:"passes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Passes) Reset()         { *m = Passes{} }
func (m *Passes) String() string { return proto.CompactTextString(m) }
func (*Passes) ProtoMessage()    {}
func (*Passes) Descriptor() ([]byte, []int) {
	return fileDescriptor_satsvc_483814a6b85abf67, []int{15}
}
func (m *Passes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Passes.Unmarshal(m, b)
}
func (m *Passes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Passes.Marshal(b, m, deterministic)
}
func (dst *Passes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Passes.Merge(dst, src)
}
func (m *Passes) XXX_Size() int {
	return xxx_messageInfo_Passes.Size(m)
}
func (m *Passes) XXX_DiscardUnknown() {
	xxx_messageInfo_Passes.DiscardUnknown(m)
}

var xxx_messageInfo_Passes proto.InternalMessageInfo

func (m *Passes) GetPasses() []*Pass {
	if m != nil {
		return m.Passes
	}
	return nil
}

func init() {
	proto.RegisterType((*SatInfos)(nil), "SatInfos")
	proto.RegisterType((*SatsInfosResponse)(nil), "SatsInfosResponse")
	proto.RegisterType((*Location)(nil), "Location")
	proto.RegisterType((*SatLocation)(nil), "SatLocation")
	proto.RegisterType((*Category)(nil), "Category")
	proto.RegisterType((*SatsLocationsResponse)(nil), "SatsLocationsResponse")
	proto.RegisterType((*CategoriesResponse)(nil), "CategoriesResponse")
	proto.RegisterType((*Observation)(nil), "Observation")
	proto.RegisterType((*SatsRequest)(nil), "SatsRequest")
	proto.RegisterType((*SatLocationFromObsRequest)(nil), "SatLocationFromObsRequest")
	proto.RegisterType((*GenPassesRequest)(nil), "GenPassesRequest")
	proto.RegisterType((*GenLocationsRequest)(nil), "GenLocationsRequest")
	proto.RegisterType((*GenLocationsResponse)(nil), "GenLocationsResponse")
	proto.RegisterType((*GenLocations)(nil), "GenLocations")
	proto.RegisterType((*Pass)(nil), "Pass")
	proto.RegisterType((*Passes)(nil), "Passes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PredictionClient is the client API for Prediction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PredictionClient interface {
	SatsInfos(ctx context.Context, in *SatsRequest, opts ...grpc.CallOption) (*SatsInfosResponse, error)
	SatsLocations(ctx context.Context, in *SatsRequest, opts ...grpc.CallOption) (Prediction_SatsLocationsClient, error)
	SatLocationFromObs(ctx context.Context, in *SatLocationFromObsRequest, opts ...grpc.CallOption) (Prediction_SatLocationFromObsClient, error)
	GenLocations(ctx context.Context, in *GenLocationsRequest, opts ...grpc.CallOption) (*GenLocationsResponse, error)
	GenPasses(ctx context.Context, in *GenPassesRequest, opts ...grpc.CallOption) (*Passes, error)
	Categories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CategoriesResponse, error)
}

type predictionClient struct {
	cc *grpc.ClientConn
}

func NewPredictionClient(cc *grpc.ClientConn) PredictionClient {
	return &predictionClient{cc}
}

func (c *predictionClient) SatsInfos(ctx context.Context, in *SatsRequest, opts ...grpc.CallOption) (*SatsInfosResponse, error) {
	out := new(SatsInfosResponse)
	err := c.cc.Invoke(ctx, "/Prediction/SatsInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictionClient) SatsLocations(ctx context.Context, in *SatsRequest, opts ...grpc.CallOption) (Prediction_SatsLocationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Prediction_serviceDesc.Streams[0], "/Prediction/SatsLocations", opts...)
	if err != nil {
		return nil, err
	}
	x := &predictionSatsLocationsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Prediction_SatsLocationsClient interface {
	Recv() (*SatsLocationsResponse, error)
	grpc.ClientStream
}

type predictionSatsLocationsClient struct {
	grpc.ClientStream
}

func (x *predictionSatsLocationsClient) Recv() (*SatsLocationsResponse, error) {
	m := new(SatsLocationsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *predictionClient) SatLocationFromObs(ctx context.Context, in *SatLocationFromObsRequest, opts ...grpc.CallOption) (Prediction_SatLocationFromObsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Prediction_serviceDesc.Streams[1], "/Prediction/SatLocationFromObs", opts...)
	if err != nil {
		return nil, err
	}
	x := &predictionSatLocationFromObsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Prediction_SatLocationFromObsClient interface {
	Recv() (*Observation, error)
	grpc.ClientStream
}

type predictionSatLocationFromObsClient struct {
	grpc.ClientStream
}

func (x *predictionSatLocationFromObsClient) Recv() (*Observation, error) {
	m := new(Observation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *predictionClient) GenLocations(ctx context.Context, in *GenLocationsRequest, opts ...grpc.CallOption) (*GenLocationsResponse, error) {
	out := new(GenLocationsResponse)
	err := c.cc.Invoke(ctx, "/Prediction/GenLocations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictionClient) GenPasses(ctx context.Context, in *GenPassesRequest, opts ...grpc.CallOption) (*Passes, error) {
	out := new(Passes)
	err := c.cc.Invoke(ctx, "/Prediction/GenPasses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictionClient) Categories(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CategoriesResponse, error) {
	out := new(CategoriesResponse)
	err := c.cc.Invoke(ctx, "/Prediction/Categories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PredictionServer is the server API for Prediction service.
type PredictionServer interface {
	SatsInfos(context.Context, *SatsRequest) (*SatsInfosResponse, error)
	SatsLocations(*SatsRequest, Prediction_SatsLocationsServer) error
	SatLocationFromObs(*SatLocationFromObsRequest, Prediction_SatLocationFromObsServer) error
	GenLocations(context.Context, *GenLocationsRequest) (*GenLocationsResponse, error)
	GenPasses(context.Context, *GenPassesRequest) (*Passes, error)
	Categories(context.Context, *empty.Empty) (*CategoriesResponse, error)
}

func RegisterPredictionServer(s *grpc.Server, srv PredictionServer) {
	s.RegisterService(&_Prediction_serviceDesc, srv)
}

func _Prediction_SatsInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictionServer).SatsInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Prediction/SatsInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictionServer).SatsInfos(ctx, req.(*SatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prediction_SatsLocations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PredictionServer).SatsLocations(m, &predictionSatsLocationsServer{stream})
}

type Prediction_SatsLocationsServer interface {
	Send(*SatsLocationsResponse) error
	grpc.ServerStream
}

type predictionSatsLocationsServer struct {
	grpc.ServerStream
}

func (x *predictionSatsLocationsServer) Send(m *SatsLocationsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Prediction_SatLocationFromObs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SatLocationFromObsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PredictionServer).SatLocationFromObs(m, &predictionSatLocationFromObsServer{stream})
}

type Prediction_SatLocationFromObsServer interface {
	Send(*Observation) error
	grpc.ServerStream
}

type predictionSatLocationFromObsServer struct {
	grpc.ServerStream
}

func (x *predictionSatLocationFromObsServer) Send(m *Observation) error {
	return x.ServerStream.SendMsg(m)
}

func _Prediction_GenLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictionServer).GenLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Prediction/GenLocations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictionServer).GenLocations(ctx, req.(*GenLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prediction_GenPasses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenPassesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictionServer).GenPasses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Prediction/GenPasses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictionServer).GenPasses(ctx, req.(*GenPassesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prediction_Categories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictionServer).Categories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Prediction/Categories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictionServer).Categories(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Prediction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Prediction",
	HandlerType: (*PredictionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SatsInfos",
			Handler:    _Prediction_SatsInfos_Handler,
		},
		{
			MethodName: "GenLocations",
			Handler:    _Prediction_GenLocations_Handler,
		},
		{
			MethodName: "GenPasses",
			Handler:    _Prediction_GenPasses_Handler,
		},
		{
			MethodName: "Categories",
			Handler:    _Prediction_Categories_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SatsLocations",
			Handler:       _Prediction_SatsLocations_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SatLocationFromObs",
			Handler:       _Prediction_SatLocationFromObs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "satsvc.proto",
}

func init() { proto.RegisterFile("satsvc.proto", fileDescriptor_satsvc_483814a6b85abf67) }

var fileDescriptor_satsvc_483814a6b85abf67 = []byte{
	// 918 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x8e, 0xed, 0x78, 0x37, 0x39, 0xf6, 0x56, 0xdd, 0xe9, 0xb6, 0x72, 0x0d, 0xd5, 0xa6, 0xc3,
	0x5f, 0x2a, 0xaa, 0x59, 0x1a, 0x24, 0x50, 0xb5, 0x42, 0x88, 0xa2, 0x52, 0x81, 0xa0, 0xad, 0x66,
	0xb9, 0xe0, 0x2e, 0x4c, 0x92, 0xd9, 0x60, 0xc9, 0xf6, 0x04, 0xcf, 0xa4, 0xea, 0xf2, 0x00, 0xbc,
	0x00, 0xe2, 0x15, 0x90, 0x78, 0x16, 0x1e, 0x83, 0x6b, 0xde, 0x01, 0xcd, 0x8f, 0x1d, 0x27, 0xd9,
	0x3f, 0x10, 0x17, 0xdc, 0xcd, 0x39, 0x73, 0x8e, 0xe7, 0x3b, 0xdf, 0x7c, 0x73, 0x8e, 0x21, 0x96,
	0x4c, 0xc9, 0x57, 0x53, 0xb2, 0xa8, 0x84, 0x12, 0xe9, 0xe1, 0x5c, 0x88, 0x79, 0xce, 0x8f, 0x8c,
	0x35, 0x59, 0x9e, 0x1e, 0xa9, 0xac, 0xe0, 0x52, 0xb1, 0x62, 0xe1, 0x02, 0xde, 0xd8, 0x0c, 0xe0,
	0xc5, 0x42, 0x9d, 0xd9, 0x4d, 0xfc, 0x9b, 0x07, 0xbd, 0x13, 0xa6, 0xbe, 0x2c, 0x4f, 0x85, 0x44,
	0xf7, 0x21, 0x2e, 0x45, 0xc5, 0x66, 0xe3, 0x72, 0x59, 0x4c, 0x78, 0x95, 0x78, 0x03, 0x6f, 0x18,
	0xd2, 0xc8, 0xf8, 0x9e, 0x1b, 0x17, 0x42, 0xd0, 0x2d, 0x59, 0xc1, 0x13, 0x7f, 0xe0, 0x0d, 0xfb,
	0xd4, 0xac, 0xb5, 0x4f, 0xe5, 0xfc, 0x51, 0x12, 0x58, 0x9f, 0x5e, 0x3b, 0xdf, 0x28, 0xe9, 0x36,
	0xbe, 0x11, 0x3a, 0x86, 0x68, 0xb9, 0x98, 0x31, 0xc5, 0xc7, 0x1a, 0x62, 0x12, 0x0e, 0xbc, 0x61,
	0x34, 0x4a, 0x89, 0x85, 0x47, 0x6a, 0x78, 0xe4, 0xdb, 0x1a, 0x3f, 0x05, 0x1b, 0xae, 0x1d, 0xf8,
	0x18, 0xf6, 0x4f, 0x98, 0x92, 0x06, 0x28, 0xe5, 0x72, 0x21, 0x4a, 0xc9, 0xd1, 0xbb, 0xd0, 0x97,
	0x4c, 0x8d, 0x33, 0xed, 0x4c, 0xbc, 0x41, 0x30, 0x8c, 0x46, 0x7d, 0x52, 0x97, 0x43, 0x7b, 0xd2,
	0xad, 0xf0, 0xf7, 0xd0, 0xfb, 0x5a, 0x4c, 0x99, 0xca, 0x44, 0x89, 0x52, 0xe8, 0xe5, 0x4c, 0x65,
	0x6a, 0x39, 0xe3, 0xa6, 0x40, 0x8f, 0x36, 0x36, 0x7a, 0x13, 0xfa, 0xb9, 0x28, 0xe7, 0x76, 0xd3,
	0x37, 0x9b, 0x2b, 0x87, 0xce, 0x64, 0xb9, 0xcb, 0x0c, 0x6c, 0x66, 0x6d, 0xe3, 0x9f, 0x3d, 0x88,
	0x4e, 0x98, 0x6a, 0x4e, 0xb9, 0x06, 0x95, 0x6d, 0x20, 0xfe, 0x65, 0x40, 0x82, 0xcb, 0x80, 0x74,
	0x37, 0x80, 0x3c, 0x81, 0xde, 0xe7, 0x4c, 0xf1, 0xb9, 0xa8, 0xce, 0xd0, 0x0d, 0xf0, 0xb3, 0x99,
	0x3b, 0xda, 0xcf, 0x66, 0x17, 0x5d, 0x9e, 0x96, 0x53, 0x12, 0x0c, 0x82, 0x61, 0x48, 0xcd, 0x1a,
	0x7f, 0x05, 0xb7, 0x35, 0xd7, 0x75, 0x31, 0x2b, 0xbe, 0x1f, 0xc1, 0x9e, 0xe6, 0x3b, 0xaf, 0x37,
	0x1c, 0xe7, 0x31, 0x69, 0x95, 0x4e, 0xb5, 0x3c, 0x9b, 0x54, 0xfc, 0x29, 0x20, 0x87, 0x27, 0xe3,
	0xab, 0x0f, 0x3d, 0x00, 0x98, 0x36, 0xde, 0xe6, 0xe6, 0x6a, 0xe0, 0xb4, 0xb5, 0x89, 0xff, 0xf0,
	0x20, 0x7a, 0x31, 0x91, 0xbc, 0x7a, 0x75, 0x6d, 0x66, 0x1f, 0x9a, 0x27, 0xd2, 0xc0, 0x34, 0xf5,
	0xea, 0xef, 0x37, 0x10, 0xa3, 0x16, 0x44, 0x94, 0xc0, 0x2e, 0xfb, 0x29, 0x2b, 0x96, 0xea, 0x07,
	0xc7, 0x74, 0x6d, 0xea, 0x5b, 0xe0, 0x39, 0xb7, 0xe7, 0x3a, 0xa2, 0x57, 0x0e, 0x74, 0x00, 0x61,
	0xc5, 0xca, 0xb9, 0x15, 0xb2, 0x47, 0xad, 0x81, 0xee, 0x01, 0x98, 0xc5, 0xb8, 0x62, 0x8a, 0x27,
	0x3b, 0x36, 0xc9, 0x78, 0x28, 0x53, 0x1c, 0x3f, 0x37, 0x32, 0x91, 0x94, 0xff, 0xb8, 0xe4, 0x52,
	0xa1, 0xb7, 0x60, 0xaf, 0x5d, 0x8c, 0xa5, 0x22, 0xa4, 0x71, 0xab, 0x1a, 0xa9, 0xaf, 0xdb, 0xf1,
	0x71, 0x66, 0x4a, 0x09, 0x69, 0x63, 0xe3, 0x5f, 0x3c, 0xb8, 0xdb, 0x22, 0xff, 0x8b, 0x4a, 0x14,
	0x2f, 0x26, 0xff, 0xec, 0xf3, 0x1f, 0xc1, 0xbe, 0x30, 0xfc, 0xf2, 0xea, 0x12, 0xca, 0x6e, 0xd6,
	0x31, 0x0d, 0x6f, 0x77, 0xa1, 0x27, 0x15, 0x5f, 0xc8, 0x71, 0x21, 0x0d, 0x71, 0x21, 0xdd, 0x35,
	0xf6, 0x37, 0x12, 0xff, 0xee, 0xc3, 0xcd, 0x67, 0xbc, 0x7c, 0xc9, 0xa4, 0xe4, 0x0d, 0x98, 0x6b,
	0x5c, 0xdc, 0xbf, 0x85, 0xf2, 0x18, 0x40, 0x2a, 0x56, 0x29, 0xdb, 0x58, 0x82, 0x2b, 0x1b, 0x4b,
	0xdf, 0x44, 0x6b, 0x1b, 0x7d, 0x0c, 0x7d, 0xa9, 0xc4, 0xc2, 0x66, 0x76, 0xaf, 0xcc, 0xec, 0xe9,
	0x60, 0x93, 0x78, 0x1f, 0x62, 0x5d, 0xee, 0x58, 0xf2, 0xa9, 0x28, 0x67, 0xd2, 0xa8, 0x20, 0xa4,
	0x91, 0xf6, 0x9d, 0x58, 0x97, 0xa6, 0xbf, 0xc8, 0xca, 0xf1, 0x4a, 0x43, 0x56, 0x0e, 0x71, 0x91,
	0x95, 0x4f, 0x6b, 0x1f, 0xfe, 0xcb, 0x83, 0x5b, 0xcf, 0x78, 0xd9, 0x7a, 0x6c, 0xff, 0x8d, 0x34,
	0xfe, 0xa7, 0xa4, 0xe0, 0x53, 0x38, 0x58, 0x2f, 0xd7, 0xb5, 0x84, 0xf7, 0x75, 0xcb, 0x5b, 0xef,
	0x2b, 0x7b, 0x64, 0x2d, 0x72, 0xb5, 0xbf, 0x75, 0x8e, 0xbf, 0x7d, 0xce, 0x77, 0x10, 0xb7, 0xb3,
	0xaf, 0x23, 0xbf, 0x77, 0xa0, 0xd7, 0x52, 0x5d, 0xb0, 0xae, 0xba, 0x66, 0x0b, 0xff, 0xea, 0x43,
	0x57, 0x4b, 0x1b, 0x3d, 0x84, 0x80, 0x99, 0xc1, 0x73, 0x15, 0x41, 0x3a, 0x4c, 0x47, 0xe7, 0x42,
	0x3a, 0x39, 0x5f, 0x1a, 0x9d, 0x0b, 0x89, 0x0e, 0x21, 0x62, 0x42, 0x8e, 0xd7, 0x3b, 0x13, 0x30,
	0x21, 0x3f, 0x73, 0xcd, 0xe9, 0x10, 0xa2, 0xbc, 0x15, 0x60, 0xdb, 0x13, 0xe4, 0xab, 0x00, 0xad,
	0x3e, 0xf6, 0xba, 0xa5, 0xbe, 0xd0, 0xa9, 0x8f, 0xbd, 0x6e, 0xd4, 0x87, 0xde, 0x86, 0x1b, 0xfa,
	0x98, 0xad, 0x96, 0x15, 0x33, 0x21, 0x69, 0xdd, 0xb5, 0x74, 0x54, 0xbe, 0x1e, 0xb5, 0x6b, 0xa3,
	0xf2, 0x56, 0x14, 0x7e, 0x0f, 0x76, 0xec, 0x8b, 0x47, 0xf7, 0x60, 0x67, 0x61, 0x56, 0xee, 0x22,
	0x43, 0xa2, 0x37, 0xa8, 0x73, 0x8e, 0xfe, 0xf4, 0x01, 0x5e, 0x56, 0x7c, 0x96, 0x4d, 0x0d, 0x86,
	0x23, 0xe8, 0x37, 0xa3, 0x1d, 0x99, 0x59, 0x52, 0x3f, 0x82, 0x14, 0x91, 0xad, 0xa1, 0x8f, 0x3b,
	0xe8, 0x31, 0xec, 0xad, 0xcd, 0xa7, 0x8d, 0xa4, 0x3b, 0xe4, 0xdc, 0xe9, 0x85, 0x3b, 0x1f, 0x78,
	0xe8, 0x09, 0xa0, 0xed, 0x76, 0x89, 0x52, 0x72, 0x61, 0x0f, 0x4d, 0x63, 0xd2, 0x9a, 0x3e, 0xe6,
	0x1b, 0x9f, 0x6c, 0x28, 0xeb, 0x80, 0x9c, 0xf3, 0x7e, 0xd3, 0xdb, 0xe4, 0x3c, 0x99, 0xe3, 0x0e,
	0x7a, 0x00, 0xfd, 0xa6, 0x37, 0xa2, 0x7d, 0xb2, 0xd9, 0x27, 0xd3, 0x5d, 0x62, 0x6d, 0xdc, 0x41,
	0xc7, 0x00, 0xab, 0xe1, 0x89, 0xee, 0x6c, 0x69, 0xe6, 0xa9, 0xfe, 0x93, 0x4b, 0x6f, 0x91, 0xed,
	0x09, 0x8b, 0x3b, 0x93, 0x1d, 0x13, 0xf6, 0xe1, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x6b,
	0xf3, 0x42, 0x2f, 0x0a, 0x00, 0x00,
}
