// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sgp4svc.proto

package sgp4svc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SatRequest struct {
	NoradNumber          int32    `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SatRequest) Reset()         { *m = SatRequest{} }
func (m *SatRequest) String() string { return proto.CompactTextString(m) }
func (*SatRequest) ProtoMessage()    {}
func (*SatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sgp4svc_9759e8530d6ab5a1, []int{0}
}
func (m *SatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatRequest.Unmarshal(m, b)
}
func (m *SatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatRequest.Marshal(b, m, deterministic)
}
func (dst *SatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatRequest.Merge(dst, src)
}
func (m *SatRequest) XXX_Size() int {
	return xxx_messageInfo_SatRequest.Size(m)
}
func (m *SatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SatRequest proto.InternalMessageInfo

func (m *SatRequest) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

type SatInfosResponse struct {
	NoradNumber          int32    `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tle1                 string   `protobuf:"bytes,3,opt,name=tle1,proto3" json:"tle1,omitempty"`
	Tle2                 string   `protobuf:"bytes,4,opt,name=tle2,proto3" json:"tle2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SatInfosResponse) Reset()         { *m = SatInfosResponse{} }
func (m *SatInfosResponse) String() string { return proto.CompactTextString(m) }
func (*SatInfosResponse) ProtoMessage()    {}
func (*SatInfosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_sgp4svc_9759e8530d6ab5a1, []int{1}
}
func (m *SatInfosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatInfosResponse.Unmarshal(m, b)
}
func (m *SatInfosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatInfosResponse.Marshal(b, m, deterministic)
}
func (dst *SatInfosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatInfosResponse.Merge(dst, src)
}
func (m *SatInfosResponse) XXX_Size() int {
	return xxx_messageInfo_SatInfosResponse.Size(m)
}
func (m *SatInfosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SatInfosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SatInfosResponse proto.InternalMessageInfo

func (m *SatInfosResponse) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

func (m *SatInfosResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SatInfosResponse) GetTle1() string {
	if m != nil {
		return m.Tle1
	}
	return ""
}

func (m *SatInfosResponse) GetTle2() string {
	if m != nil {
		return m.Tle2
	}
	return ""
}

type Location struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude             float64  `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_sgp4svc_9759e8530d6ab5a1, []int{2}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

type SatLocationRequest struct {
	NoradNumber          int32                `protobuf:"varint,1,opt,name=norad_number,json=noradNumber,proto3" json:"norad_number,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SatLocationRequest) Reset()         { *m = SatLocationRequest{} }
func (m *SatLocationRequest) String() string { return proto.CompactTextString(m) }
func (*SatLocationRequest) ProtoMessage()    {}
func (*SatLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sgp4svc_9759e8530d6ab5a1, []int{3}
}
func (m *SatLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatLocationRequest.Unmarshal(m, b)
}
func (m *SatLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatLocationRequest.Marshal(b, m, deterministic)
}
func (dst *SatLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatLocationRequest.Merge(dst, src)
}
func (m *SatLocationRequest) XXX_Size() int {
	return xxx_messageInfo_SatLocationRequest.Size(m)
}
func (m *SatLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SatLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SatLocationRequest proto.InternalMessageInfo

func (m *SatLocationRequest) GetNoradNumber() int32 {
	if m != nil {
		return m.NoradNumber
	}
	return 0
}

func (m *SatLocationRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*SatRequest)(nil), "SatRequest")
	proto.RegisterType((*SatInfosResponse)(nil), "SatInfosResponse")
	proto.RegisterType((*Location)(nil), "Location")
	proto.RegisterType((*SatLocationRequest)(nil), "SatLocationRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PredictionClient is the client API for Prediction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PredictionClient interface {
	SatInfos(ctx context.Context, in *SatRequest, opts ...grpc.CallOption) (*SatInfosResponse, error)
	SatLocation(ctx context.Context, in *SatLocationRequest, opts ...grpc.CallOption) (*Location, error)
}

type predictionClient struct {
	cc *grpc.ClientConn
}

func NewPredictionClient(cc *grpc.ClientConn) PredictionClient {
	return &predictionClient{cc}
}

func (c *predictionClient) SatInfos(ctx context.Context, in *SatRequest, opts ...grpc.CallOption) (*SatInfosResponse, error) {
	out := new(SatInfosResponse)
	err := c.cc.Invoke(ctx, "/Prediction/SatInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictionClient) SatLocation(ctx context.Context, in *SatLocationRequest, opts ...grpc.CallOption) (*Location, error) {
	out := new(Location)
	err := c.cc.Invoke(ctx, "/Prediction/SatLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PredictionServer is the server API for Prediction service.
type PredictionServer interface {
	SatInfos(context.Context, *SatRequest) (*SatInfosResponse, error)
	SatLocation(context.Context, *SatLocationRequest) (*Location, error)
}

func RegisterPredictionServer(s *grpc.Server, srv PredictionServer) {
	s.RegisterService(&_Prediction_serviceDesc, srv)
}

func _Prediction_SatInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictionServer).SatInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Prediction/SatInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictionServer).SatInfos(ctx, req.(*SatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prediction_SatLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SatLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictionServer).SatLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Prediction/SatLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictionServer).SatLocation(ctx, req.(*SatLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Prediction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Prediction",
	HandlerType: (*PredictionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SatInfos",
			Handler:    _Prediction_SatInfos_Handler,
		},
		{
			MethodName: "SatLocation",
			Handler:    _Prediction_SatLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sgp4svc.proto",
}

func init() { proto.RegisterFile("sgp4svc.proto", fileDescriptor_sgp4svc_9759e8530d6ab5a1) }

var fileDescriptor_sgp4svc_9759e8530d6ab5a1 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4f, 0xb4, 0x30,
	0x10, 0x86, 0x97, 0x5d, 0xbe, 0x2f, 0x30, 0x68, 0xa2, 0xf5, 0x42, 0x88, 0x89, 0x6b, 0x4f, 0x7b,
	0x30, 0x25, 0xa2, 0x7f, 0xc2, 0xc4, 0x18, 0x53, 0xbc, 0x6b, 0x81, 0x2e, 0x21, 0x42, 0xcb, 0xd2,
	0xc1, 0xdf, 0x6f, 0x28, 0xdb, 0x5d, 0xa3, 0x97, 0xbd, 0x75, 0x9e, 0x99, 0x37, 0x33, 0x3c, 0xc0,
	0xb9, 0xa9, 0xfb, 0x47, 0xf3, 0x55, 0xb2, 0x7e, 0xd0, 0xa8, 0x93, 0x9b, 0x5a, 0xeb, 0xba, 0x95,
	0xa9, 0xad, 0x8a, 0x71, 0x9b, 0x62, 0xd3, 0x49, 0x83, 0xa2, 0xeb, 0xe7, 0x01, 0x9a, 0x02, 0xe4,
	0x02, 0xb9, 0xdc, 0x8d, 0xd2, 0x20, 0xb9, 0x85, 0x33, 0xa5, 0x07, 0x51, 0xbd, 0xab, 0xb1, 0x2b,
	0xe4, 0x10, 0x7b, 0x6b, 0x6f, 0xf3, 0x8f, 0x47, 0x96, 0xbd, 0x58, 0x44, 0x77, 0x70, 0x91, 0x0b,
	0x7c, 0x52, 0x5b, 0x6d, 0xb8, 0x34, 0xbd, 0x56, 0x46, 0x9e, 0x10, 0x23, 0x04, 0x7c, 0x25, 0x3a,
	0x19, 0x2f, 0xd7, 0xde, 0x26, 0xe4, 0xf6, 0x3d, 0x31, 0x6c, 0xe5, 0x7d, 0xbc, 0x9a, 0xd9, 0xf4,
	0xde, 0xb3, 0x2c, 0xf6, 0x0f, 0x2c, 0xa3, 0x1f, 0x10, 0x3c, 0xeb, 0x52, 0x60, 0xa3, 0x15, 0x49,
	0x20, 0x68, 0x05, 0x36, 0x38, 0x56, 0xd2, 0xae, 0xf1, 0xf8, 0xa1, 0x26, 0xd7, 0x10, 0xb6, 0x5a,
	0xd5, 0x73, 0x73, 0x69, 0x9b, 0x47, 0x30, 0x25, 0x45, 0xbb, 0x4f, 0xae, 0xe6, 0xa4, 0xab, 0x69,
	0x0d, 0x24, 0x17, 0xe8, 0x96, 0x9c, 0x6e, 0x83, 0x30, 0xf0, 0x27, 0xa3, 0x76, 0x5b, 0x94, 0x25,
	0x6c, 0xd6, 0xcd, 0x9c, 0x6e, 0xf6, 0xe6, 0x74, 0x73, 0x3b, 0x97, 0x7d, 0x02, 0xbc, 0x0e, 0xb2,
	0x6a, 0x4a, 0xfb, 0x31, 0x77, 0x10, 0x38, 0x97, 0x24, 0x62, 0xc7, 0xff, 0x90, 0x5c, 0xb2, 0xdf,
	0x8e, 0xe9, 0x82, 0xa4, 0x10, 0xfd, 0x38, 0x92, 0x5c, 0xb1, 0xbf, 0x27, 0x27, 0x21, 0x73, 0x84,
	0x2e, 0x8a, 0xff, 0xf6, 0x8c, 0x87, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xb9, 0xf4, 0xb8,
	0x14, 0x02, 0x00, 0x00,
}
