---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: linter
  image: golangci/golangci-lint:v1.26.0
  commands:
  - golangci-lint run -v

- name: testbuild
  image: golang:alpine
  commands:
  - apk add --no-cache musl-dev build-base git
  - go test ./...
  - make sataas
  - make satcli

...
