kind: pipeline
name: default

steps:
  - name: test
    image: golang:alpine
    environment:
      CC: musl-gcc
    commands:
      - apk add --no-cache git make build-base
      - go test ./...
      - make sataas
      - make satcli
