kind: pipeline
type: kubernetes
name: prtriggered

steps:
  - name: build
    image: golang:alpine
    commands:
      - echo "from pr"
    when:
      event:
        - pull_request
---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: golang:alpine
    commands:
      - apk add --no-cache musl-dev build-base git curl npm
      - make cicd-build 

  - name: build_image
    #image: plugins/docker
    image: akhenakh/drone-kaniko
    settings:
      repo: akhenakh/sataas
      dry_run: true
      dockerfile: cmd/sataas/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password


  - name: deploy
    image: golang:alpine
    commands:
      - echo "salut"
    when:
      event:
      - promote
      target:
      - production
