kind: pipeline
name: default

steps:
  - name: test
    image: golang:alpine
    commands:
      - apk add --no-cache musl-dev
      - CC=$(which musl-gcc) go test ./...
      - CC=$(which musl-gcc) make sataas
      - CC=$(which musl-gcc) make satcli
