kind: pipeline
name: default

steps:
  - name: test
    image: golang:alpine
    commands:
      - apk add --no-cache musl-dev build-base git
      - go test ./...
      - make sataas
      - make satcli
