run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 3m

  timeout: 4m

  skip-files:
    - gen.go
    - cppsgp4/cppsgp4.go

      # modules-download-mode: vendor

linters:
  disable:
    - wsl
    - gochecknoglobals
    - gomnd
    - funlen
    - gocognit
    - scopelint
    - goerr113
  presets:
    - bugs
    - unused
    - complexity
    - style

linters-settings:
  errcheck:
    exclude: .errcheck_excludes.txt
